# Change these first
owner: notchaase # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: notchaase

sites:
  - name: WWW
    url: https://chse.dev
  - name: Mail
    url: https://mail.chse.dev
    
assignees: # Users to assign downtime issues (optional)
  - chxseh
  
status-website:
  cname: status.chse.dev
  name: Uptime
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
